#!/bin/sh

gitleaksEnabled=$(git config --bool hooks.gitleaks)

cmd="gitleaks --verbose --redact --pretty"

# Is gitleaks installed?
which gitleaks 2>&1 >/dev/null
if [ $? -ne 0 ]
then
  echo "gitleaks is not installed. Please fix that."
  exit 1
fi

if [ "$gitleaksEnabled" = "true" ]; then
    $cmd
    if [ $? -eq 1 ]; then
cat <<\EOF
Error: gitleaks has detected sensitive information in your changes.
If you know what you are doing you can disable this check using:

    git config hooks.gitleaks false

EOF
exit 1
    fi
fi
