* My /n/th literal emacs configuration     :TOC_3:
  - [[#initial-setup][Initial setup]]
    - [[#personal-details][Personal details]]
    - [[#talk-to-my-ssh-agent][Talk to my ssh-agent]]
    - [[#wheres-my-org][Where's my org?]]
    - [[#better-defaults][Better Defaults]]
    - [[#secrets-because-some-things-dont-belong-in-git][Secrets, because some things don't belong in git]]
  - [[#look-and-feel][Look and feel]]
    - [[#configure-base-fonts][Configure base fonts]]
    - [[#theme-and-modeline][Theme and modeline]]
    - [[#use-nicer-window-titles][Use nicer window titles.]]
    - [[#fancy-splash-screen][Fancy Splash Screen]]
    - [[#beacon][Beacon]]
    - [[#golden-ratio][Golden ratio]]
    - [[#zoom][Zoom]]
    - [[#stripe-buffer][Stripe buffer]]
    - [[#which-key][Which Key]]
    - [[#keyboard-shortcuts][Keyboard shortcuts]]
  - [[#packages][Packages]]
    - [[#flyspell-lazy][Flyspell lazy]]
  - [[#text-editing][Text editing]]
    - [[#flyspell][Flyspell]]
  - [[#languages][Languages]]
    - [[#plaintext][Plaintext]]
  - [[#package-management][Package management]]
  - [[#snippets-and-templates][Snippets and templates]]
  - [[#eshell-configuration][EShell configuration.]]
  - [[#orgmode][Orgmode]]
    - [[#configuration][configuration]]
    - [[#fancy-priorities][Fancy priorities.]]
    - [[#agenda-configuration][Agenda configuration.]]
    - [[#refile][Refile]]
    - [[#org-roam][org-roam]]
    - [[#journal][Journal]]
  - [[#magit][Magit]]
    - [[#pretty-magit][Pretty Magit]]
    - [[#magit-todos][Magit TODOs]]
    - [[#magit-forge][Magit Forge]]

** Initial setup
#+begin_src emacs-lisp :tangle yes
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

#+end_src

*** Personal details
My name and email address. Various things use this, such as Git and GPG.
#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Andy Bold"
      user-mail-address "{{@@ env['work_git_email'] @@}}")

#+end_src

*** Talk to my ssh-agent
#+begin_src emacs-lisp :tangle yes
(exec-path-from-shell-copy-env "GPG_TTY")
(exec-path-from-shell-copy-env "SSH_AUTH_SOCK")

#+end_src

*** Where's my org?
#+begin_src emacs-lisp :tangle yes
(setq org-directory "/Users/andyb/Google Drive File Stream/My Drive/org")

#+end_src

*** Better Defaults
**** Display line numbers? (Yes.)
I used to set this to =t= for boring old line numbers. I'm taking relative for a bit of a spin for a while to see how it feels.
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type 'relative)

#+end_src

Today I discovered [[https://tecosaur.github.io/emacs-config/config.html][Teco's Doom config]]. There is a lot of Good Stuff, including this chunk of happiness.
#+begin_src emacs-lisp :tangle yes
(setq-default
 delete-by-moving-to-trash t                      ; Delete files to trash
 tab-width 2                                      ; Set width for tabs
 uniquify-buffer-name-style 'forward              ; Uniquify buffer names
 window-combination-resize t                      ; take new window space from all other windows (not just current)
 x-stretch-cursor t)                              ; Stretch cursor to the glyph width

(setq undo-limit 80000000                         ; Raise undo-limit to 80Mb
      evil-want-fine-undo t                       ; By default while in insert all changes are one big blob. Be more granular
      auto-save-default t                         ; Nobody likes to loose work, I certainly don't
      inhibit-compacting-font-caches t            ; When there are lots of glyphs, keep them in memory
      truncate-string-ellipsis "…")               ; Unicode ellispis are nicer than "...", and also save /precious/ space

(delete-selection-mode 1)                         ; Replace selection when inserting text
(display-time-mode 1)                             ; Enable time in the mode-line

(global-subword-mode 1)                           ; Iterate through CamelCase words

#+end_src

**** Fullscreen
Also cribbed from Teco, automatically start in fullscreen. Saves some mousing and clicking. One change is that the original checks if =initial-window-system= is =x=. I use MacOS, and the equivalent value is =ns=.
#+begin_src emacs-lisp :tangle yes
(if (eq initial-window-system 'ns)                 ; if started by emacs command or desktop file
    (toggle-frame-maximized)
  (toggle-frame-fullscreen))

#+end_src

**** Customisations
More Teco goodness. Instead of saving settings changed by Emacs =customise= into =init.el=, save them to a standalone file. This keeps the Doom =init.el= clea. It will only be loaded if it exists.

I rarely do this, but occasionally I'll use it to test something that I'm not ready to put into here.
#+begin_src emacs-lisp :tangle yes
(setq-default custom-file (expand-file-name ".custom.el" doom-private-dir))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

**** Windows
More from the fecund world of Teco. The first thing I almost always do after splitting the window is switch to a different buffer. This automatically prompts for a buffer to show in the new frame.

Start by entering the new window.
#+begin_src emacs-lisp :tangle yes
(setq evil-vsplit-window-right t
      evil-split-window-below t)
#+end_src

Then call Ivy to show the buffers I have open.
#+begin_src emacs-lisp :tangle yes
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit)
  (+ivy/switch-buffer))
#+end_src

And tell Ivy to show a preview of the buffer being selected.
#+begin_src emacs-lisp :tangle yes
(setq +ivy-buffer-preview t)
#+end_src

*** Secrets, because some things don't belong in git
#+begin_src emacs-lisp :tangle yes
(defun ab-load-file-if-exists (&rest paths)
  "Load files when they exists."
  (dolist (file-path paths)
   (when (file-exists-p file-path)
    (load file-path))))

(ab-load-file-if-exists "~/.emacs-secrets.el")

#+end_src

** Look and feel
*** Configure base fonts
#+begin_src emacs-lisp :tangle yes
(setq doom-font "Fira Code"
      doom-variable-pitch-font "Overpass"
      doom-serif-font (font-spec :family "IBM Plex Mono" :weight 'light))

#+end_src

*** Theme and modeline
#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'doom-Iosvkem)

#+end_src

Tweak the modeline to remove unnecessary info. Start by making "this file has been edited" less shouty and red.
#+begin_src emacs-lisp :tangle yes
(custom-set-faces!
  '(doom-modeline-buffer-modified :foreground "orange"))
#+end_src

Remove the file encoding info. UTF-8 is the default. I'm rarely going to be using anything else these days.
#+begin_src emacs-lisp :tangle yes
(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8, so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (unless (or (eq buffer-file-coding-system 'utf-8-unix)
                          (eq buffer-file-coding-system 'utf-8)))))

(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)
#+end_src

I'm going to stop going on about Teco. If it looks nice then it's probably stolen from his config. This sets some nicer default buffer names. Teco's idea.
#+begin_src emacs-lisp :tangle yes
(setq doom-fallback-buffer-name "► Doom"
      +doom-dashboard-name "► Doom")
#+end_src

*** Use nicer window titles.
Just the buffer name, followed by the project if it's applicable.
#+begin_src emacs-lisp :tangle yes
(setq frame-title-format
    '(""
      (:eval
       (if (s-contains-p org-roam-directory (or buffer-file-name ""))
           (replace-regexp-in-string ".*/[0-9]*-?" "🢔 " buffer-file-name)
         "%b"))
      (:eval
       (let ((project-name (projectile-project-name)))
         (unless (string= "-" project-name)
           (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src

*** Fancy Splash Screen
This is nice. More Teco.
#+begin_src emacs-lisp :tangle yes
(defvar fancy-splash-image-template
  (expand-file-name "misc/splash-images/blackhole-lines-template.svg" doom-private-dir)
  "Default template svg used for the splash image, with substitutions from ")
(defvar fancy-splash-image-nil
  (expand-file-name "misc/splash-images/transparent-pixel.png" doom-private-dir)
  "An image to use at minimum size, usually a transparent pixel")

(setq fancy-splash-sizes
  `((:height 500 :min-height 50 :padding (0 . 4) :template ,(expand-file-name "misc/splash-images/blackhole-lines-0.svg" doom-private-dir))
    (:height 440 :min-height 42 :padding (1 . 4) :template ,(expand-file-name "misc/splash-images/blackhole-lines-0.svg" doom-private-dir))
    (:height 400 :min-height 38 :padding (1 . 4) :template ,(expand-file-name "misc/splash-images/blackhole-lines-1.svg" doom-private-dir))
    (:height 350 :min-height 36 :padding (1 . 3) :template ,(expand-file-name "misc/splash-images/blackhole-lines-2.svg" doom-private-dir))
    (:height 300 :min-height 34 :padding (1 . 3) :template ,(expand-file-name "misc/splash-images/blackhole-lines-3.svg" doom-private-dir))
    (:height 250 :min-height 32 :padding (1 . 2) :template ,(expand-file-name "misc/splash-images/blackhole-lines-4.svg" doom-private-dir))
    (:height 200 :min-height 30 :padding (1 . 2) :template ,(expand-file-name "misc/splash-images/blackhole-lines-5.svg" doom-private-dir))
    (:height 100 :min-height 24 :padding (1 . 2) :template ,(expand-file-name "misc/splash-images/emacs-e-template.svg" doom-private-dir))
    (:height 0   :min-height 0  :padding (0 . 0) :file ,fancy-splash-image-nil)))

(defvar fancy-splash-sizes
  `((:height 500 :min-height 50 :padding (0 . 2))
    (:height 440 :min-height 42 :padding (1 . 4))
    (:height 330 :min-height 35 :padding (1 . 3))
    (:height 200 :min-height 30 :padding (1 . 2))
    (:height 0   :min-height 0  :padding (0 . 0) :file ,fancy-splash-image-nil))
  "list of plists with the following properties
  :height the height of the image
  :min-height minimum `frame-height' for image
  :padding `+doom-dashboard-banner-padding' to apply
  :template non-default template file
  :file file to use instead of template")

(defvar fancy-splash-template-colours
  '(("$colour1" . keywords) ("$colour2" . type) ("$colour3" . base5) ("$colour4" . base8))
  "list of colour-replacement alists of the form (\"$placeholder\" . 'theme-colour) which applied the template")

(unless (file-exists-p (expand-file-name "theme-splashes" doom-cache-dir))
  (make-directory (expand-file-name "theme-splashes" doom-cache-dir) t))

(defun fancy-splash-filename (theme-name height)
  (expand-file-name (concat (file-name-as-directory "theme-splashes")
                            (symbol-name doom-theme)
                            "-" (number-to-string height) ".svg")
                    doom-cache-dir))

(defun fancy-splash-clear-cache ()
  "Delete all cached fancy splash images"
  (interactive)
  (delete-directory (expand-file-name "theme-splashes" doom-cache-dir) t)
  (message "Cache cleared!"))

(defun fancy-splash-generate-image (template height)
  "Read TEMPLATE and create an image if HEIGHT with colour substitutions as  ;described by `fancy-splash-template-colours' for the current theme"
    (with-temp-buffer
      (insert-file-contents template)
      (re-search-forward "$height" nil t)
      (replace-match (number-to-string height) nil nil)
      (dolist (substitution fancy-splash-template-colours)
        (beginning-of-buffer)
        (while (re-search-forward (car substitution) nil t)
          (replace-match (doom-color (cdr substitution)) nil nil)))
      (write-region nil nil
                    (fancy-splash-filename (symbol-name doom-theme) height) nil nil)))

(defun fancy-splash-generate-images ()
  "Perform `fancy-splash-generate-image' in bulk"
  (dolist (size fancy-splash-sizes)
    (unless (plist-get size :file)
      (fancy-splash-generate-image (or (plist-get size :file)
                                       (plist-get size :template)
                                       fancy-splash-image-template)
                                   (plist-get size :height)))))

(defun ensure-theme-splash-images-exist (&optional height)
  (unless (file-exists-p (fancy-splash-filename
                          (symbol-name doom-theme)
                          (or height
                              (plist-get (car fancy-splash-sizes) :height))))
    (fancy-splash-generate-images)))

(defun get-appropriate-splash ()
  (let ((height (frame-height)))
    (cl-some (lambda (size) (when (>= height (plist-get size :min-height)) size))
             fancy-splash-sizes)))

(setq fancy-splash-last-size nil)
(setq fancy-splash-last-theme nil)
(defun set-appropriate-splash (&optional frame)
  (let ((appropriate-image (get-appropriate-splash)))
    (unless (and (equal appropriate-image fancy-splash-last-size)
                 (equal doom-theme fancy-splash-last-theme)))
    (unless (plist-get appropriate-image :file)
      (ensure-theme-splash-images-exist (plist-get appropriate-image :height)))
    (setq fancy-splash-image
          (or (plist-get appropriate-image :file)
              (fancy-splash-filename (symbol-name doom-theme) (plist-get appropriate-image :height))))
    (setq +doom-dashboard-banner-padding (plist-get appropriate-image :padding))
    (setq fancy-splash-last-size appropriate-image)
    (setq fancy-splash-last-theme doom-theme)
    (+doom-dashboard-reload)))

(add-hook 'window-size-change-functions #'set-appropriate-splash)
(add-hook 'doom-load-theme-hook #'set-appropriate-splash)
#+end_src

*** Beacon
Beacon helps you to find your cursor when you are scrolling around. It is installed in =packages.el=
#+begin_src emacs-lisp :tangle yes
(setq beacon-color +evil--emacs-cursor-color + -1)
(setq beacon-blink-when-point-moves-vertically 10)
(setq beacon-dont-blink-major-modes '(dashboard-mode))
(beacon-mode 1)
#+end_src

*** Golden ratio
I like splitting my editor window so that I can see more than one file that I'm working on. Sometimes it's essential. For example, if I'm working on a Terraform module, and I want to keep an eye on several bits of relevant info.

I don't like the way that Emacs handles this. Window sizes are usually 'wrong', and I spend too much time resizing them. Golden Ratio might fix this for me. I'm starting out with letting GR handle things automatically, but a max width of 120 characters.

There are some buffers that should never be scaled. They are added to =golden-ratio-exclude-buffer-regexp=.

That being said, Zoom is set up below and this block is currently disabled. Zoom might do a better job. Golden Ratio also appears to be unmaintained at the moment.
#+begin_src emacs-lisp :tangle no
(golden-ration-mode 1)
(setq golden-ratio-auto-scale t)
(setq golden-ratio-max-width 120)
(add-to-list 'golden-ratio-exclude-buffer-regexp "^\\*[hH]elm.*")
(add-to-list 'golden-ratio-exclude-buffer-regexp "^\\*vterm.*")
(add-to-list 'golden-ratio-exclude-buffer-regexp "^\\*ediff.*")

#+end_src

*** Zoom
Automatically resize the active window.

If the frame size is >1280 then use 100 columns and 75% of the frame height. Otherwise, make it a 50%x50% split.
#+begin_src emacs-lisp :tangle yes
(zoom-mode)
(defun size-callback ()
  (cond ((> (frame-pixel-width) 1280) '(100 . 0.75))
        (t                            '(0.5 . 0.5))))

(custom-set-variables
 '(zoom-size 'size-callback)
 '(zoom-ignored-buffer-name-regexps '("^*ediff.*")))

#+end_src

*** Stripe buffer
Use stripe-y buffer lists.

#+begin_src emacs-lisp :tangle yes
;; hl-line (higher priority stripes) fix:
(defadvice sb/redraw-region (after stripe-set-priority activate)
  (when (or stripe-buffer-mode stripe-table-mode)
    (dolist (overlay sb/overlays)
      (overlay-put overlay 'priority -100))))

#+end_src
*** Which Key
Doom has =which-key= configured out of the box. =which-key-posframe= causes =which-key= windows to work as a popover centred in the emacs frame.
#+begin_src emacs-lisp :tangle yes
(setq which-key-idle-secondary-delay 0)
;;(which-key-side-window-max-height 0.99)

(which-key-mode)
(which-key-posframe-mode)

(set-face-attribute 'which-key-posframe-border nil :background "slategray")
(set-face-attribute 'which-key-posframe nil :background "darkslategray")

#+end_src

The default delay for the =which-key= popup is a little tardy. Let's speed things up a touch.
#+begin_src emacs-lisp :tangle yes
(setq which-key-idle-delay 0.5)
#+end_src

And we don't need all the mentions of =evil= in the =which-key= prompts. I know I'm using it, so let's make things less verbose.
#+begin_src emacs-lisp :tangle yes
(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "◂\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "◃\\1"))
   ))
#+end_src

*** Keyboard shortcuts
#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-c =") 'er/expand-region)

#+end_src


** Packages
*** Flyspell lazy
Prevents flyspell being a CPU hog. This is actually in =packages.el=, but noted here for posterity
#+begin_src emacs-lisp :tangle no
(package! flyspell-lazy :pin "3ebf68cc9e...")
#+end_src

** Text editing
*** Flyspell
Enable the =flyspell-lazy= package that was referenced earlier.
#+begin_src emacs-lisp :tangle yes
(after! flyspell (require 'flyspell-lazy) (flyspell-lazy-mode 1))
#+end_src

** Languages
*** Plaintext
If ANSI colors are there, use them.
#+begin_src emacs-lisp :tangle yes
(after! text-mode
  (add-hook! 'text-mode-hook
    ;; Apply ANSI color codes
    (with-silent-modifications
      (ansi-color-apply-on-region (point-min) (point-max)))))
#+end_src

** Package management
I let Doom manage my packages. If I need to look something up then I use Paradox
#+begin_src emacs-lisp :tangle yes
(setq paradox-github-token "{{@@ env['personal_github_token'] @@}}")
#+end_src


** Snippets and templates
I need to move these to yasnippets at some point.

Start by making sure that org-tempo is enabled.
#+begin_src emacs-lisp :tangle yes
(require 'org-tempo)

#+end_src

Set up some templates for Babel.
#+begin_src emacs-lisp :tangle yes
(tempo-define-template "plain-src"
                       '("#+begin_src ?\n\n" > "#+end_src")
                       "<s"
                       "Insert a generic source code template")

(tempo-define-template "lisp-block"
                       '("#+begin_src emacs-lisp :tangle yes\n?\n" > "#+end_src")
                       "<sl"
                       "Insert an embedded Lisp block for literate emacs.d")

(tempo-define-template "k8s"
                       '("#+name: k8s\n#+begin_src shell :tangle no :results output\n?\n" > "#+end_src")
                       "<sk"
                       "Insert a, non-tangled, k8s block")

(tempo-define-template "shell-code"
                       '("#+begin_src shell :tangle no :results value raw :results value drawer :session" > "\n\n#+end_src")
                       "<ss"
                       "Shell code block, with raw results")

(tempo-define-template "properties-block"
                       '(":PROPERTIES:\n" > ":END:")
                       "<PROP"
                       "Orgmode properties block")
(tempo-define-template "python-code"
                       '("#+begin_src python :tangle no :results value raw :results value drawer :session" > "\n\n#+end_src")
                       "<sp"
                       "Python code block, with raw results")
(tempo-define-template "plantuml"
                       '("#+begin_src plantuml :tangle no :results value raw :results value drawer :session" > "\n\n#+end_src")
                       "<puml"
                       "Plantuml")

#+end_src

** EShell configuration.
When I need a quick shell I use VTerm. This is for org-babel.

Hook Ansi colour filtering into shell mode
#+begin_src emacs-lisp :tangle yes
(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)

#+end_src


** Orgmode
If I need to keep anything confidential in a .org then it gets GPG encrypted. Configure Org to deal with that when it happens.

Add .org.gpg file suffix to the auto-mode list
#+begin_src emacs-lisp :tangle yes
(add-to-list 'auto-mode-alist '("\\.org\\.gpg" . org-mode))

#+end_src

*** ToDo configuration
Configure todo keywords.
#+begin_src emacs-lisp :tangle yes
(setq org-todo-keywords
  '((sequence "TODO(t)" "PROJ(p)" "STRT(s!)" "WAIT(w@/!)" "HOLD(h@/!)" "|" "DONE(d!)" "KILL(k!)")
    (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")))

#+end_src

Keep a log of when a task was completed.
#+begin_src emacs-lisp :tangle yes
(setq org-log-into-drawer "LOGBOOK")

#+end_src

*** Fancy priorities.
#+begin_src emacs-lisp :tangle yes
(after! org-fancy-priorities
  (add-hook! org-mode . org-fancy-priorities-mode)
  (setq org-fancy-priorities-list '("⚡" "⬆" "⬇" "☕")))

#+end_src

*** Agenda configuration.
Tell Agenda mode to include .org.gpg files.
#+begin_src emacs-lisp :tangle yes
(unless (string-match-p "\\.gpg" org-agenda-file-regexp)
  (setq org-agenda-file-regexp
    (replace-regexp-in-string "\\\\\\.org" "\\\\.org\\\\(\\\\.gpg\\\\)?"
      org-agenda-file-regexp)))
#+end_src

Expand Agenda targets to include .org.gpg. Refile uses these below to build it's list of places it can save to.
#+begin_src emacs-lisp :tangle yes
(add-to-list 'org-agenda-files (expand-file-name "~/Documents/org/*\\.org\\.gpg"))
#+end_src

*** Refile
Refile targets include the current file and any file contributing to the agenda - up to 9 levels deep.
#+begin_src emacs-lisp :tangle yes
(setq org-refile-targets (quote ((nil :maxlevel . 4)
                                (org-agenda-files :maxlevel . 4)
                                )))
#+end_src

Use full outline paths for refile targets.
#+begin_src emacs-lisp :tangle yes
(setq org-refile-use-outline-path t)

#+end_src

Refile targets complete directly with IDO.
#+begin_src emacs-lisp :tangle yes
(setq org-outline-path-complete-in-steps nil)

#+end_src

Allow refile to create parent tasks with confirmation.
#+begin_src emacs-lisp :tangle yes
(setq org-refile-allow-creating-parent-nodes (quote confirm))
#+end_src

Exclude DONE state tasks from refile targets.
#+begin_src emacs-lisp :tangle yes
(defun ab/verify-refile-target ()
  "Exclude todo keywords with a done state from refile targets."
   (not (member (nth 2 (org-heading-components)) org-done-keywords)))

(setq org-refile-target-verify-function 'ab/verify-refile-target)
#+end_src

*** org-roam
I haven't invested enough (any) time in properly getting to grips with
org-roam, so it's disabled for now.

#+begin_src emacs-lisp :tangle no

(setq org-roam-directory "~/Documents/org/launchdarkly")

(after! org-roam
       (map! :leader
           :prefix "n"
           :desc "org-roam" "l" #'org-roam
           :desc "org-roam-insert" "i" #'org-roam-insert
           :desc "org-roam-switch-to-buffer" "b" #'org-roam-switch-to-buffer
           :desc "org-roam-find-file" "f" #'org-roam-find-file
           :desc "org-roam-show-graph" "g" #'org-roam-show-graph
           :desc "org-roam-insert" "i" #'org-roam-insert
           :desc "org-roam-capture" "c" #'org-roam-capture))

(require 'company-org-roam)
   (use-package company-org-roam
     :when (featurep! :completion company)
     :after org-roam
     :config
     (set-company-backend! 'org-mode '(company-org-roam company-yasnippet company-dabbrev)))

(after! org-roam
 (setq org-roam-encrypt-files t)
 (setq org-roam-ref-capture-templates
   '(("r" "ref" plain (function org-roam-capture--get-point)
       "%?"
       :file-name "websites/${slug}.org.gpg"
       :head "-*- epa-file-encrypt-to: ("andy.bold@me.com") -*-
,#+TITLE: ${title}
   ,#+ROAM_KEY: ${ref}
   - source :: ${ref}"
       :unnarrowed t)))

 (setq org-roam-capture-templates
   '(("d" "default" plain (function org-roam--capture-get-point)
      "%?"
      :file-name "%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)"
      :head "-*- epa-file-encrypt-to: (\"andy.bold@me.com\") -*-

,#+TITLE: ${title}\n"
      :unnarrowed t))))
#+end_src

*** Journal
#+begin_src emacs-lisp :tangle yes
(use-package! org-journal
      :bind
      ("C-c j n" . org-journal-new-entry)
      ("C-c j <" . org-journal-open-previous-entry)
      ("C-c j >" . org-journal-open-next-entry)
  :custom

  ;; (org-journal-enable-encryption t)
  (org-journal-dir "/Users/andyb/Google Drive File Stream/My Drive/org/journal/")
      (org-journal-date-prefix "#+TITLE: ")
      (org-journal-file-format "%Y-%m-%d.org")
      (org-journal-date-format "%A, %d %B %Y"))
    (setq org-journal-enable-agenda-integration t)
    (setq org-journal-time-format "")

  (defun org-journal-file-header-func (time)
  "Custom function to create journal header."
  (concat
    (pcase org-journal-file-type
      (`daily "-*- mode: org; fill-column: 78 -*-\n#+STARTUP: folded\n")
      (`weekly "-*- mode: org; fill-column: 78 -*-\n#+STARTUP: folded\n")
      (`monthly "-*- mode: org; fill-column: 78 -*-\n#+STARTUP: folded\n")
      (`yearly "-*- mode: org; fill-column: 78 -*-\n#+STARTUP: folded\n"))))

  (setq org-journal-file-header 'org-journal-file-header-func)
#+end_src

Add a hook for org-download...
#+begin_src emacs-lisp :tangle yes
(add-hook 'dired-mode-hook 'org-download-enable)
#+end_src

...and enable it.
#+begin_src emacs-lisp :tangle yes

(after! org-journal
  (org-download-enable)
  (setq org-download-method "directory"
    org-download-heading-lvl nil))
#+end_src

** Magit
Magit is the other reason that Emacs is so sticky for me. I haven't come across any IDE that does Git as well as magit does.

*** Pretty Magit
Might as well make it look good, then.

#+begin_src emacs-lisp :tangle yes
(require 'dash)

(defmacro pretty-magit (WORD ICON PROPS &optional NO-PROMPT?)
  "Replace sanitized WORD with ICON, PROPS and by default add to prompts."
  `(prog1
     (add-to-list 'pretty-magit-alist
                  (list (rx bow (group ,WORD (eval (if ,NO-PROMPT? "" ":"))))
                        ,ICON ',PROPS))
     (unless ,NO-PROMPT?
       (add-to-list 'pretty-magit-prompt (concat ,WORD ": ")))))

(setq pretty-magit-alist nil)
(setq pretty-magit-prompt nil)
(pretty-magit "Feature" ? (:foreground "slate gray" :height 1.2))
(pretty-magit "Add"     ? (:foreground "#375E97" :height 1.2))
(pretty-magit "Fix"     ? (:foreground "#FB6542" :height 1.2))
(pretty-magit "Clean"   ? (:foreground "#FFBB00" :height 1.2))
(pretty-magit "Docs"    ? (:foreground "#3F681C" :height 1.2))
(pretty-magit "WIP"    ?🚧 (:foreground "#3F681C" :height 1.2))
(pretty-magit "master"  ? (:box t :height 1.2) t)
(pretty-magit "origin"  ? (:box t :height 1.2) t)

(defun add-magit-faces ()
  "Add face properties and compose symbols for buffer from pretty-magit."
  (interactive)
  (with-silent-modifications
    (--each pretty-magit-alist
      (-let (((rgx icon props) it))
        (save-excursion
          (goto-char (point-min))
          (while (search-forward-regexp rgx nil t)
            (compose-region
             (match-beginning 1) (match-end 1) icon)
            (when props
              (add-face-text-property
               (match-beginning 1) (match-end 1) props))))))))

(advice-add 'magit-status :after 'add-magit-faces)
(advice-add 'magit-refresh-buffer :after 'add-magit-faces)
#+end_src

Configure Ivy to prompt for a leader
#+begin_src emacs-lisp :tangle yes
(setq use-magit-commit-prompt-p nil)
(defun use-magit-commit-prompt (&rest args)
  (setq use-magit-commit-prompt-p t))

(defun magit-commit-prompt ()
  "Magit prompt and insert commit header with faces."
  (interactive)
  (when use-magit-commit-prompt-p
    (setq use-magit-commit-prompt-p nil)
    (insert (ivy-read "Commit Type " pretty-magit-prompt
                      :require-match t :sort t :preselect "Add: "))
    ;; Or if you are using Helm...
    ;; (insert (helm :sources (helm-build-sync-source "Commit Type "
    ;;                          :candidates pretty-magit-prompt)
    ;;               :buffer "*magit cmt prompt*"))
    ;; I haven't tested this but should be simple to get the same behaior
    (add-magit-faces)
    (evil-insert 1)  ; If you use evil
    ))

(remove-hook 'git-commit-setup-hook 'with-editor-usage-message)
(add-hook 'git-commit-setup-hook 'magit-commit-prompt)
(advice-add 'magit-commit :after 'use-magit-commit-prompt)
#+end_src

*** Magit TODOs
Configure Magit to show TODO items in the Magit buffer
#+begin_src emacs-lisp :tangle yes
(add-hook! magit-mode
           (magit-todos-mode))

#+end_src

*** Magit Forge
Interact with Git forges like Github via Magit. E.g., handle PRs.
#+begin_src emacs-lisp :tangle yes
(defadvice magit-pull-from-upstream (after forge-pull activate)
  (forge-pull))
#+end_src
